import type { DocumentCandidate } from "../../src/lib/documents/types";

const pcmaSeed = {
  slug: "policia-civil-do-maranhao-2012",
  title: "Polícia Civil do Maranhão — 2012",
  organization: "Polícia Civil do Estado do Maranhão",
  organizationSlug: "policia-civil-do-estado-do-maranhao-ma",
  organizationAcronym: "PC-MA",
  state: "MA",
  status: "ENCERRADO" as const,
  officialUrl: "https://conhecimento.fgv.br/concursos/maranhao12/policia-civil",
  provider: "document_collector" as const,
  externalId: "fgv-maranhao12-policia-civil",
};

const fgv = {
  name: "FGV Conhecimento",
  domain: "conhecimento.fgv.br",
  type: "EXAM_BOARD" as const,
  official: true,
  reliabilityScore: 0.99,
};

export const documentPilotCandidates: DocumentCandidate[] = [
  {
    key: "acari-2026-edital-005",
    contestSlug: "prefeitura-de-acari-rn-295413",
    kind: "EDITAL",
    semanticType: "ABERTURA",
    title: "Edital nº 005/2026 — Concurso Público da Prefeitura de Acari",
    sourceUrl: "https://www.acari.rn.gov.br/storage/content/publicacoes/editais/2791/arquivos/editais-20260924214138RQ0b.pdf",
    discoveryUrl: "https://www.acari.rn.gov.br/publicacoes/editais/concurso-publico-2026",
    publishedAt: "2026-09-24T21:39:00-03:00",
    source: { name: "Prefeitura Municipal de Acari", domain: "acari.rn.gov.br", type: "OFFICIAL", official: true, reliabilityScore: 1 },
    notice: { number: "005/2026", year: 2026 },
  },
  {
    key: "pcma-2012-edital-02",
    contestSlug: pcmaSeed.slug,
    contestSeed: pcmaSeed,
    kind: "EDITAL",
    semanticType: "ABERTURA",
    title: "Edital nº 02 — Polícia Civil do Maranhão 2012",
    sourceUrl: "https://conhecimento.fgv.br/sites/default/files/concursos/edital_02_-_policia_civil_13_09_06.pdf",
    discoveryUrl: pcmaSeed.officialUrl,
    publishedAt: "2012-10-10T00:00:00-03:00",
    source: fgv,
    notice: { number: "02", year: 2012 },
  },
  {
    key: "pcma-2012-investigador-prova-tipo-1",
    contestSlug: pcmaSeed.slug,
    contestSeed: pcmaSeed,
    kind: "PROVA",
    semanticType: "OBJETIVA_TIPO_1",
    title: "Prova objetiva — Investigador de Polícia — Tipo 1",
    sourceUrl: "https://conhecimento.fgv.br/sites/default/files/concursos/policia_civil_investigador_de_policia_caderno_01.pdf",
    discoveryUrl: pcmaSeed.officialUrl,
    publishedAt: "2012-12-04T00:00:00-03:00",
    source: fgv,
    exam: {
      year: 2012,
      boardName: "Fundação Getulio Vargas",
      boardAcronym: "FGV",
      boardSlug: "fgv",
      boardSite: "https://conhecimento.fgv.br/",
      role: "Investigador de Polícia",
      shift: null,
      questionCount: 70,
    },
  },
  {
    key: "pcma-2012-investigador-gabarito-definitivo",
    contestSlug: pcmaSeed.slug,
    contestSeed: pcmaSeed,
    kind: "GABARITO",
    semanticType: "DEFINITIVO",
    title: "Gabarito definitivo — Investigador de Polícia",
    sourceUrl: "https://conhecimento.fgv.br/sites/default/files/concursos/segep12_policia_civil_-_investigador_de_policia_-_gabaritos_0.pdf",
    discoveryUrl: pcmaSeed.officialUrl,
    publishedAt: "2012-12-19T00:00:00-03:00",
    source: fgv,
    relatedProofKey: "pcma-2012-investigador-prova-tipo-1",
  },
];
